#!/usr/bin/env bash


# @param: name of the DB
args_db_name=${1}

# @param: username of the DB user
args_db_user=${2}

# @param: password of the DB user
args_db_pass=${3}

# @param: allowed hostname
args_db_host=${4}


# suppress prompts
export DEBIAN_FRONTEND=noninteractive

# install MySQL
sudo -E yum install -y mysql-server > /dev/null
#start mysql service
sudo -E chkconfig mysqld on > /dev/null
sudo -E service mysqld restart > /dev/null
# create database
mysql -uroot -e "create database ${args_db_name};" > /dev/null

# create user, and grant all permissions to new DB
mysql -uroot -e "grant all privileges on ${args_db_name}.* to '${args_db_user}'@'${args_db_host}' identified by '${args_db_pass}';" > /dev/null
